services:
  mysql_db:
    image: mysql:8.0
    container_name: votovivo_db
    environment:
      MYSQL_DATABASE: votovivo
      MYSQL_ROOT_PASSWORD: test
    command:
      - --innodb-buffer-pool-size=64M
      - --max-connections=50
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      interval: 5s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          memory: 300M

  api:
    build: .
    container_name: votovivo_api
    environment:
      DATABASE_URL: mysql://root:test@mysql_db:3306/votovivo
      PORT: 3001
      NODE_OPTIONS: --max-old-space-size=256
    ports:
      # Expõe a API na porta 80 do servidor para a Cloudflare acessar
      - "80:3001" 
    depends_on:
      mysql_db:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma generate &&
        node dist/server.js
      "
    deploy:
      resources:
        limits:
          memory: 300M

volumes:
  mysql_data:
